### PR TITLE
BFS USING C

### PR DESCRIPTION
**Pull request by DIVYA-KUMARI1**
IMPLEMENTATION OF BFS USING C

### CODE REVIEW

**Review by sparsh-99 — APPROVED** [review]
Try to implement DS using C++, Java or Python @DIVYA-KUMARI1. But for hacktober, it seems good

**Comment by DIVYA-KUMARI1** [comment]
Please Merge my Pull request

**Comment by sparsh-99** [comment]
> Please Merge my Pull request

I don't have write access to the repo. Only the owner can do it.

**Review by G1Joshi — APPROVED** [review]

**Comment by G1Joshi** [comment]
Welcome to the world of C0D1NG 🚀

**Pull request merged**
